### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by tmnyoni** [mgrsskls/typing-effect#20] opened 2022-02-24 09:10 UTC
Please can you make more tutorials.

**Comment by mgrsskls** [comment] 2022-02-24 17:48
Hi @tmnyoni,

there is not really anything else to document than the information which is already in the readme.
But if you tell me what you need exactly, I can try to help! Are you experiencing any issues? Or where are you stuck?

**Comment by tmnyoni** [comment] 2022-02-24 20:29
Okay, I am having trouble with using ` .then ` after returning the promise. I am using the library on ReactJS, so I want to change the state of components after typing is done.

```js
const [typingDone, setTypingDone] = useState(false)
useEffect(() => {
    typingEffect(
        Array.from(document.querySelectorAll("[data-typing-effect]"))
    ).then(setTypingDone(!typingDone);
})
```

But I keep getting an error, I am not sure if I am using it wrongly, but I saw it on the demo code where you did this
```js
.then(() => document.querySelector("footer").removeAttribute("hidden"));
```

#### The error
![image](https://user-images.githubusercontent.com/58740910/155602444-d6e872de-8c7e-4b13-999a-471403944bcc.png)

then I did this
```js
 Array.from(document.querySelectorAll("[data-typing-effect]"))
    ).then(()=>setTypingDone(!typingDone);
```

Atleast this time around it typed, then after it has done, it throw the error, unlike at first, where after loading the page it throw the error.

**Comment by mgrsskls** [comment] 2022-02-25 10:50
Sorry, the code example for using `.then()` in the README was wrong, it needs to be like this of course: https://github.com/mgrsskls/typing-effect/commit/a2b654a3c8b206323c713230fe0fe891cab9bd44 So, you call the `.then()` on `typingEffect`, not on `Array.from()` (as you did it in your React example).

I am not really familiar with react, but I will set up a project later to see if I can reproduce that.

Just to clarify: Are you importing the project via `import typingEffect from "typing-effect"`?

**Comment by mgrsskls** [comment] 2022-02-25 13:20
@tmnyoni I tried it in a small react component and it works for me when calling `typingEffect(…)` inside `componentDidMount`, and then passing a `ref` to the animated element to `typingEffect()`. But I am really not that familiar with react, so there might be better ways.

I will close this issue for now, but let me know if you need more help!

**Closed as completed by mgrsskls** 2022-02-25 13:20 UTC

**Comment by tmnyoni** [comment] 2022-02-25 22:00
#### Just to help someone who will have the same problem in the future.

I have finally found the solution to the problem. So, when using ReactJS functional components, when you are using the `useEffect` hook, you need to also include the dependency array like so,

```js
useEffect(() => {
    typingEffect(
        Array.from(document.querySelectorAll("[data-typing-effect]"))
    ).then(setTypingDone(!typingDone);
}, [])
```

If you don't put that `[]` it throws that error.
